twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes

    exception_controller: App\Controller\CustomExceptionController::showAction

    globals:
        ga_traking: '%ga_tracking%'
