<?php
/**
 * Created by PhpStorm.
 * User: aminebetari
 * Date: 18/04/20
 * Time: 19:54
 */

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use App\Form\DataTransformer\TagModelTransformer;
use App\Form\DataTransformer\TagViewTransformer;

class TagType extends AbstractType
{
    private $tagModelTransformer;

    private $tagViewTransformer;

    /**
     * TagType constructor.
     * @param $tagModelTransformer
     * @param $tagViewTransformer
     */
    public function __construct(TagModelTransformer $tagModelTransformer, TagViewTransformer $tagViewTransformer)
    {
        $this->tagModelTransformer = $tagModelTransformer;
        $this->tagViewTransformer  = $tagViewTransformer;
    }


    public function getParent()
    {
        return  TextType::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
      //   parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->addViewTransformer($this->tagModelTransformer)->addModelTransformer($this->tagViewTransformer);
    }

}